### ISSUE TITLE
Security question formatting

### ISSUE THREAD

**Issue by gtomitsuka** [DevDoodle/DevDoodle-Public#4]
I don't know how shall I format my answer to Format (x + 6)².
I tried `x² + 6²`, `x^2 + 36`, `x² + 36`, nothing works....

Although I like that this prevents people younger than 10 from joining DevDoodle, really, you guys should migrate to Captchas.

**Comment by bjb568** [comment]
First inner outer last.

**Comment by gtomitsuka** [comment]
Oh how dumb can I be :P Thanks anyway!
