### ISSUE TITLE
In the help page, 'The' is misspelt

### ISSUE THREAD

**Issue by eyeballcode** [DevDoodle/DevDoodle-Public#5]
> Tho programs can't be directly edited, they can be forked to add functionality. Forking a program creates an editable clone of it owned by the forker.

It should be this:

> The programs can't be directly edited, they can be forked to add functionality. Forking a program creates an editable clone of it owned by the forker.

**Comment by ProgramFOX** [comment]
Actually this is @bjb568's way of spelling "though", which causes some confusion here. Yet another reason to avoid text speak.

**Comment by bjb568** [comment]
"Tho" isn't text speak, it's a perfectly logical alternate spelling of though. I prefer to not say "ugh" all the time for no reason :)
